DeltaXSetup.UI/Controllers/ActorController.cs
using BusinessServices.Actor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntities;
using DeltaXSetup.UI.Logging;

namespace DeltaXSetup.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorServices _ActorServices;
        private readonly IDeltaXBaseController _ControllerBase;
        Log logger = new Log("ActorController");

        #region Public Constructor        
        /// <summary>  
        /// Public constructor to initialize product service instance  
        /// </summary>  
        public ActorController(IActorServices actorServices)
        {
            _ActorServices = actorServices;
            _ControllerBase = new DeltaXBaseController();
        }

        #endregion 
        //
        // GET: /Default1/

        public ActionResult Index()
        {
            var actors = _ActorServices.GetActorList();
            if (actors != null && actors.Count > 0)
            {
                return View(actors);
            }
            return RedirectToAction("Create");
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id)
        {
            var actor = _ActorServices.GetActorById(id);
            return View(actor);
        }

        //
        // GET: /Default1/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        public ActionResult Create(ActorEntity actor)
        {
            try
            {
                decimal result = _ActorServices.AddActor(actor);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                logger.monitoringLogger.Error("Error", ex.InnerException);
                return View();
            }
        }

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id)
        {
            var actor = _ActorServices.GetActorById(id);
            return View(actor);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, ActorEntity actor)
        {
            try
            {
                _ActorServices.UpdateActor(id, actor);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                logger.monitoringLogger.Error("ActorUpdate Error:", ex);
                ModelState.AddModelError("Update Error", "Update Failed");
                return View();
            }
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id)
        {
            //var result = _ActorServices.DeleteActor(id);
            return RedirectToAction("Index");
        }

        ////
        //// POST: /Default1/Delete/5

        //[HttpPost]
        //public ActionResult Delete(int id, ActorEntity actor)
        //{
        //    try
        //    {
        //        _ActorServices.DeleteActor(
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

DeltaXSetup.UI/Controllers/MoviesController.cs
using BusinessEntities;
using BusinessServices.Actor;
using BusinessServices.Movies;
using BusinessServices.Producer;
using DeltaXSetup.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeltaXSetup.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesServices _MoviesServices;
        private readonly IDeltaXBaseController _ControllerBase;
        private readonly IActorServices _ActorServices;
        private readonly IProducerServices _ProducerServices;
        private Movie model;

        #region Public Constructor
        /// <summary>  
        /// Public constructor to initialize product service instance  
        /// </summary>  
        public MoviesController(IMoviesServices MoviesServices, IActorServices actorServices, IProducerServices producerServices)
        {
            _MoviesServices = MoviesServices;
            _ControllerBase = new DeltaXBaseController();
            _ActorServices = actorServices;
            _ProducerServices = producerServices;
            GetDependentData();
        }
        //
        // GET: /Movies/

        public ActionResult Index()
        {
            var movies = _MoviesServices.GetMovieList();
            if (movies != null && movies.Count > 0)
            {
                return View(movies);
            }
            return RedirectToAction("Create");
        }

        //
        // GET: /Movies/Details/5

        public ActionResult Details(int id)
        {
            var movie = _MoviesServices.GetMovieById(id);
            return View(movie);
        }

        private IEnumerable<SelectListItem> GetActors()
        {
            var actors = _ActorServices
                        .GetActorList()
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.ActorId.ToString(),
                                    Text = x.Name
                                });

            return new SelectList(actors, "Value", "Text");
        }

        private IEnumerable<SelectListItem> GetProducers()
        {
            var producers = _ProducerServices
                        .GetProducerList()
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.ProducerId.ToString(),
                                    Text = x.Name
                                });

            return new SelectList(producers, "Value", "Text");
        }

        private void GetDependentData()
        {
             model = new Movie
            {
                ActorData = GetActors(),
                ProducerData = GetProducers()
            };
        }

        //
        // GET: /Movies/Create
        public ActionResult Create()
        {            
            return View(model);
        }

        //
        // POST: /Movies/Create

        [HttpPost]
        public ActionResult Create(Movie collection, HttpPostedFileBase postedFile)
        {
            try
            {
                List<MovieActorEntity> movieActors = new List<MovieActorEntity>();
                List<MovieProducerEntity> producer = new List<MovieProducerEntity>();
                if (Request.Form["MovieData.MovieActors"].Length > 0)
                {
                    var selectedActors = Request.Form["MovieData.MovieActors"].Split(',');
                    foreach (var item in selectedActors)
                    {
                        movieActors.Add(new MovieActorEntity { ActorId = Convert.ToInt32(item), MovieId = collection.MovieData.MovieId });
                    }
                }
                else
                {
                    ModelState.AddModelError("Actors", "Atleast One Actor is required.!");
                    return View();
                }
                if (Request.Form["MovieData.MovieProducers"].Length > 0)
                {
                    var selectedProducer = Request.Form["MovieData.MovieProducers"];
                    producer.Add(new MovieProducerEntity { ProducerId = Convert.ToInt32(selectedProducer), MovieId = collection.MovieData.MovieId });
                }
                else {
                    ModelState.AddModelError("Producer", "Producer is required.!");
                    return View(model);
                }
                MovieEntity movie = new MovieEntity
                {
                    MovieId = collection.MovieData.MovieId,
                    Name=collection.MovieData.Name,
                    Plot = collection.MovieData.Plot,
                    ReleaseYear = collection.MovieData.ReleaseYear,
                    File = postedFile,
                    MovieActors = movieActors,
                    MovieProducers = producer
                };

                decimal result = _MoviesServices.AddMovie(movie);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View(model);
            }
        }

        //
        // GET: /Movies/Edit/5

        public ActionResult Edit(int id)
        {
            var movie = _MoviesServices.GetMovieById(id);
            var model = new Movie
            {
                MovieData = movie,
                ActorData = GetActors(),
                ProducerData = GetProducers()
            };
            return View(model);
        }

        //
        // POST: /Movies/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, Movie collection, HttpPostedFileBase postedFile)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Movies/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Movies/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion
    }
}

DeltaXSetup.UI/Views/Movies/Create.cshtml
@model DeltaXSetup.Models.Movie

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Movie</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.MovieId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.MovieId)
            @Html.ValidationMessageFor(model => model.MovieData.MovieId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.Name)
            @Html.ValidationMessageFor(model => model.MovieData.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.ReleaseYear)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.ReleaseYear)
            @Html.ValidationMessageFor(model => model.MovieData.ReleaseYear)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.Plot)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.Plot)
            @Html.ValidationMessageFor(model => model.MovieData.Plot)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.Poster)
        </div>
        <div class="editor-field">
            <input type="file" name="postedFile"/>
            @Html.ValidationMessageFor(model => model.MovieData.Poster)
        </div>
        <div class="editor-label">
            @Html.Label("Actors")
        </div>
        <div class="editor-field">
            @Html.ListBoxFor(m => m.MovieData.MovieActors, Model.ActorData)
            @Html.ValidationMessage("Please select one or more Actor(s)")
        </div>
        <div class="editor-label">
            @Html.Label("Producer")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.MovieData.MovieProducers, Model.ProducerData)
            @Html.ValidationMessage("Please select a Producer")
        </div>
        <br />
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")  |  @Html.ActionLink("Add Actor", "Create","Actor")  |  @Html.ActionLink("Add Producer", "Create","Producer")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeltaXSetup.UI/Views/Movies/Edit.cshtml
@model DeltaXSetup.Models.Movie

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <fieldset>
        <legend>Movie</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.MovieId)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.MovieData.MovieId)
            @Html.ValidationMessageFor(model => model.MovieData.MovieId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.Name)
            @Html.ValidationMessageFor(model => model.MovieData.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.ReleaseYear)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.ReleaseYear)
            @Html.ValidationMessageFor(model => model.MovieData.ReleaseYear)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.Plot)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieData.Plot)
            @Html.ValidationMessageFor(model => model.MovieData.Plot)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieData.Poster)
        </div>
        <div class="editor-field">
            <input type="file" name="postedFile"/>
            @Html.ValidationMessageFor(model => model.MovieData.Poster)
        </div>
        <div class="editor-label">
            @Html.Label("Actors")
        </div>
        <div class="editor-field">
            @Html.ListBoxFor(m => m.MovieData.MovieActors, Model.ActorData)
            @Html.ValidationMessage("Please select one or more Actor(s)")
        </div>
        <div class="editor-label">
            @Html.Label("Producer")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.MovieData.MovieProducers, Model.ProducerData)
            @Html.ValidationMessage("Please select a Producer")
        </div>
        <br />
        <p>
            <input type="submit" value="Update" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeltaXSetup.UI/Views/Movies/Index.cshtml
@model IEnumerable<BusinessEntities.MovieEntity>

@{
    ViewBag.Title = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MovieId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Poster)
        </th>
        <th>
            @Html.DisplayName("Actors")
        </th>
        <th>
            @Html.DisplayName("Producer")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Plot)
            </td>
            <td>
                <img src= "@Url.Content("\\MovieImages\\" + item.Poster)" height="30" alt="Image" />
            </td>
            <td>
                @if (item.MovieActors != null)
                {
                    @foreach (var actrs in item.MovieActors)
                    {
                        @Html.DisplayFor(m => actrs.Actor.Name)
                    }
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedBy)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.MovieId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MovieId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MovieId })
            </td>
        </tr>
    }

</table>